apiVersion: v1
kind: Service
metadata:
  name: django-dev-service
spec:
  type: ClusterIP
  
  selector:
    app: django-dev

  ports:
    - name: http-port-mapping
      port: 80 
      targetPort: 8000 
      protocol: TCP
