apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cnpg-app-user
  namespace: cnpg-dev
spec:
  encryptedData:
    password: AgBfvufSOrJAye4el+rX7W6eifIvmhRsd3vLLdeiaSPO3E/CQ/delnvR615VoGY5O55k0NQ967WR54DPH3u5PSLHVN0qeveb6bmLneycCfEE9w4TV1BnYKZbSiRTPG3IYIB+txkJOIMqgfSf7rOnG7NWEfUlwqqRd8rA04eStrsB3rLEbRF/vqz+9Bxpm5P3pcQ8Pxuczi6UEYzKKd1NdhgKKdTgvqaVVHk2IgfuNwHD1bJZWcufLlVm2ldmAwqjGMYrghWo83Q/3jOg9hXlequo6kz8NmsFLoqbv25F2VOgDB5uUtfov9xdLISEge43CY0G1h8oE4r9qTX4DtipzKBD1y5ckqwOEp9zN3z3Y0DML5UeTG7ETci9xZMPfPRkPJ8GuoZTUXbLIfpvf5XHudm4g9ctl4N/xyjfqUH5BBekNdUb2kKA7hv9zlqBE0p/hYlS8bWkpnGeUFaSHxOLRR3TFod0ASgSsjFYmmC+KbwuJzMg+Iia680I8Cfd7r1BXz0vZuxBPuwuS1OskZmjjlPU0+u7QwEvwhlneyEK1zlSLg44rjdzaQV5asFT1STNGRO+0OapkCQO/OtWXxFjYYA2NRn2HYw8DZX9vNmwx730+Pyy6gEET8dizAiyAA+O3pLotKvdiAJ4gfa9xbFjcUR+EKX/pZEB1y/rqTiAIR4Ns6b/drFEuskqKsonmw9DDNK9bcQVtJDm2S41lw==
    user: AgBvxHYTSIc9mWT8nTQIrRjJ13fYo8Uybgo3XPq8d4wSXfyii+0Hmaava9kvBfVkVC7Rl77VMSlBhCdbmIFLcC41XUbftpNwrXSl2TLqCLj/OWjiLM10HPvSZF9fnhxZqcskoFJaNZHrmeczDefpnx56cXE12xbZoZCW7FNlIdDhFab3yLMGJ9pwOOQkmuYWsuSFS0XnfPe/n9Ok3HDt7Z2HulWw6UBfP53CCBObapU+ndwEbRunCkffvufArwC6ZItqFUVGrdOelUA3ohSoh1rUtDGGcarwcg5UwmQx9PlltoB5XgNlunRs7+84MtFZ3KSb2orRYb62XgpMaxKJE5l/Jf9Np+K2pdrkr0M4LGGrjzX+Stzyw3gHNRw9CK90TGloK66usR/4d+qb7enx1/8ELlVldNYtlwngy6HLM1eMykiMGgeO19IeRcO/Y3WHHlH6cvf+NwcpQvjON8s3ijHHJCekq6EBe3mWBCnFD114HgWgUdbqNJvoBtvPylROm4mgvqqofWUUwiQCunGaM8qBpgjL2cfTFB2+oLoV471YgVDaCoJzdTaKZ6U5E1djZGw5TryOkjGKIuVaInrqCRGO60NYSDsAtRXxvDTLfhg3Nk6FzkS4VJzgOIjAjW58L8RJ5letiUXCjHSECwyDRahPP/gAvYe6RuyDDAcDCUIESprDEWeG7be9pkpZ2QPIHJIokx4=
  template:
    metadata:
      name: cnpg-app-user
      namespace: cnpg-dev
